# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Reudismam Rolim
tagline:             ''
description:         ''
url:                 reudismam.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Reudismam Rolim
  url:               https://twitter.com/reudismam
  email:             reudismam@copin.ufcg.edu.br
  
#Sidebar
github:
  repo               https://github.com/reudismam/Refazer

# Custom vars
version:             1.0.0
